### PR TITLE
change main class of main file, remove (), now run very good

### PR DESCRIPTION
**Pull request by clauparra**
review the change of main class in main file

### CODE REVIEW

**Review by kakarbo — CHANGES_REQUESTED** [review]
comprobar si funciona bien

**Review by Cristhian-Carbonell — CHANGES_REQUESTED** [review]
the change this good, compare the function very good

**Comment by clauparra** [comment]
the test function, if run very good

**Review by Cristhian-Carbonell — APPROVED** [review]
perfect

**Review by kakarbo — APPROVED** [review]
excelent

**Pull request merged**
